const content = [
    {
        "title":"SENIOR SOFTWARE ENGINEER - VIDEO SERVICES PLATFORM TEAM",
        "subtitle":"Alula, St. Paul, Minnesota, October 2020 – Current",
        "body":"Led mixed team of 5 remote contractors and FTEs consisting of software engineers and quality assurance analysts. Transferred ownership of infrastructure and code for the video services platform from contractors to internal team. Optimized video processing which reduced AWS EC2 compute costs by 80%. Identified and implemented changes to reduce AWS S3 storage costs by 35%. Evaluated multiple incident management software tools. Integrated incident management software into the organizations monitoring and alerting software. Architected, implemented, and load tested new data ingest pipeline for video platform using Kafka to increase scalability, visibility, and ensure system is fault tolerant. Designed and implemented provider agnostic platform to increase speed to market and decrease integration time. Worked with multiple camera providers to ensure hardware and firmware meet Alula’s specifications. Maintained, monitored, and scaled core infrastructure for organization (MSK Cluster, RDS Postgres instances). Performed database migration in order to consolidate data centers. Implemented HLS (HTTP Live Streaming). Structured the team around scrum/agile fundamentals. Worked with key business stakeholders to build and prioritize backlog. Interviewed, onboarded, and mentored a growing team of software engineers. Primary code utilization included Node.js, Jest, ffmpeg, and Terraform. Amazon Web Services: ECS Fargate, MSK, ECR, EC2 (VPC, ALB, etc), S3, RDS (Postgres), Redis, SQS, and SNS."
    },
    {
        "title":"FULL STACK SOFTWARE ENGINEER - ALULA CONNECT TEAM",
        "subtitle":"Alula, St. Paul, Minnesota, September 2019 – September 2020",
        "body": "Architected and implemented a new time-series data pipeline for organization using Amazon MSK (Kafka), wrote Terraform automation scripts to deploy necessary infrastructure for both the Kafka cluster and consumer ECS cluster. Utilized Terraform to build new monitoring platform for organization, consisting of Prometheus and Grafana, hosted and deployed in AWS. Implemented Prometheus service discoverer for ECS Fargate tasks. Implemented prometheus exporter for Burrow to monitor consumer group metrics. Enhanced and maintained multiple responsive web applications for home automation and smart security platform. Designed, implemented, and tested conditional rendering pattern to facilitate higher application maintainability and scalability (Angular and React compatible). Enhanced and maintained TypeScript library to provide reusable code for multiple applications. Led security initiatives by planning, analyzing, and architecting solutions across web and platform teams. Built out initial patterns and code base for consumer web application using React.js and Redux. Migrated features to new smart security platform to retire old application. Enhanced CI/CD pipeline with automated deployments. Implemented chat bot to facilitate QA processes using the Hubot framework. Primary code utilization included React.js, Redux, TypeScript, Angular, JavaScript, Postgres, Puppeteer, Enzyme, Jest, and Terraform. Amazon Web Services: ECS Fargate, MSK, ECR, EC2 (VPC, ALB, etc), S3, EFS, and CodePipeline."
    },
    {
        "title":"SOFTWARE ENGINEER II - NAVISPHERE VISION TEAM",
        "subtitle":"C.H. Robinson, Eden Prairie, Minnesota, January 2018 - Current",
        "body":"Enhanced and maintained eCommerce application that provides customers a view into their global supply chain. Organized and led team of 5 engineers to build custom Alexa Skill and presented it to c-level executives, received budget to expand voice app. Worked closely with data scientists to provide in-app predictive analytics, researched 3rd party APIs, and created proof of concepts. Implemented new customers on a strict deadline. Streamlined customer implementations by designing, implementing, and testing new web application. Reduced customer implementation timelines by leveraging software and driving standardization. Built software to consume multiple sources of data from enterprise service bus (RabbitMQ, Kafka). Worked with infrastructure team to migrate our application to the cloud (Azure). Rewrote application from AngularJS to React.js with Redux. Built npm package to support authentication and authorization that is used across all micro services. As lead engineer on team I mentored a growing team of engineers. Improved teams interview process for multiple roles (SE, BA, QA, PM) and led technical phone screens and on-site interviews. Primary code utilization included React.js, Redux, AngularJS, Node.js (Hapi.js), Docker, SQL, MongoDB, Elasticsearch, Enzyme, Jest, Nightwatch.js, and C# (ServiceStack)."
    },
    {
        "title":"SOFTWARE ENGINEER I - GLOBAL FORWARDING TEAM",
        "subtitle":"C.H. Robinson, Eden Prairie, Minnesota, May 2016 - December 2017",
        "body":"Worked on a team of 5 to design and implement micro-services to send and receive messages from U.S. Customs (ABI CATAIR). Refactored Pre-Arrival Processing System (PAPS) Angular web application with a responsive, mobile first design to enhance UX across wide range of devices used by truck drivers. Contributed to team of ~20 developers by leading Angular training sessions, being DevOps Advocate, and defining code standards for web applications. Built nuget package to support Role Based Access Control (RBAC) using Auth0 and ServiceStack request attributes and plugins. Built shared Angular component library using npm. Leveraged unit tests and automated acceptance(e2e) tests to ensure code quality via CI/CD pipeline. Mentored interns as part of the Intern Program Committee. Primary code utilization included HTML5, Bootstrap, Angular, Protractor.js, Jasmine, C#, ServiceStack, and SQL."
    },
    {
        "title":"PROGRAMMER ANALYST INTERN - GLOBAL FORWARDING TEAM",
        "subtitle":"C.H. Robinson, Eden Prairie, Minnesota, May 2015 - May 2016",
        "body":"Gathered requirements from users, designed, implemented, and tested web application to support team's software deployment process. Used AngularJS, SQL, ServiceStack, C# to develop web application. Built WPF application to reprocess messages, used by our support team. Worked remotely for half of the internship where I contributed to sprint work along side scrum team. Sprint work included enhancing and maintaining large VB .NET application and building out new web applications to support the needs of the growing Global Forwarding Division. Presented products/work to executives, managers, and various teams."
    },
    {
        "title":"SOFTWARE ENGINEER",
        "subtitle":"TenEx, LLC, Platteville, Wisconsin , February 2015 - August 2015",
        "body":"Designed and implemented analytics solution to help understand user behavior and rate of adoption. Created daily and weekly reports using Java and MySql with Slack integrations."
    },
    {
        "title":"SOFTWARE ENGINEER INTERN",
        "subtitle":"Danfoss, Loves Park, Illinois, May 2014 - August 2014",
        "body":"Designed and implemented embedded Wi-Fi communication system with mobile interface. Prototyped using ST Discovery Kit microcontroller and Wi-Fi module. Primary code utilization included HTML5, CSS3, JavaScript, and C."
    }
];
export default content;