const content = [
    {
        "title":"TEAM LEAD - MARKETPLACE",
        "subtitle":"Sundae, San Francisco, California, Remote, March 2022 – July 2023",  
        "body":"Completed end-to-end development for new product feature requests, including everything from requirements gathering, leading critical design conversations across teams, full-stack development, to on-time production release. Planned and executed projects, documented requirements, timelines, deliverables, and decisions. Proactively communicated progress to key stakeholders and identified and resolved roadblocks. Led project after-action review to drive continuous improvement. Organized and led cross team trainings, established centralized documentation, and documented key processes and knowledge to build a cross-functional team.\n\nReduced customer acquisition costs through the development and refinement of a web lead funnel, analyzing drop-out rates and increasing lead conversions. Evaluated third-party scheduling software by creating proof of concepts and securing budget approval from leadership. Engaged with the vendor to integrate scheduling software (Calendly), wrote code to integrate software into web lead funnel and Salesforce. Onboarded internal sales and operations teams to newly integrated scheduling software. Created documentation for off-shore consulting team to implement user analytics tracking.\n\nImplemented a feature that led to $650,000 revenue in less than 2 months. Implemented an automatic offer engine for investor bidding. Acquired proficiency in Salesforce development (APEX) and administration. Troubleshot and provided solutions for performance issues and decreased latency. Collaborated with data engineering team to integrate data and models. Improved interview process by ensuring relevant and effective questions were asked. Conducted interviews for multiple team roles. Streamlined onboarding process, reducing time required for new employee integration. Primary technologies utilized: AWS, JavaScript (React.js, Node.js), Postgres, Salesforce."
    },
    {
        "title":"FOUNDER, FOUNDING ENGINEER, ENGINEERING MANAGER",
        "subtitle":"WaWe, LLC, Minneapolis, Minnesota, Part-time, June 2020 – Current",  
        "body":"Client/Product: mait.love, AI dating app (January 2023 - June 2023); Contract CTO - Evaluated and selected third-party facial recognition software, contacted vendors, and negotiated pricing. Created proof of concepts and built the UI and API from scratch. Collaborated with a UI/UX designer, implemented a multi-role experience for users, admins, and super- admins. Developed lead funnel tracking, usage analytics, and integrated Stripe for payments. To meet project requirements, hired and trained three engineers to ensure the completion of the MVP within the designated timeline and budget. Hired and trained admin to utilize the admin software we built for order fulfillment. Created marketing video for launch. Technologies utilized: React.js, Node.js, MongoDB, AWS, Google Analytics, Hotjar, and Auth0.\n\nClient/Product: wave.pyrt.com, twitter growth marketing software (January 2023); Software Consultant - Conducted full stack development. Implement provided UI/UX design on top of existing API, extended existing API to fulfill client requirements. Collaborated with client and UX designer throughout development to address feedback. Hired additional engineer within budget to deliver project in extremely short time frame (2 weeks). Successfully launched MVP and post- launch, we scaled the tool to handle N campaigns. Technologies utilized: React.js, Node.js, Next.js, MongoDB, and Google Analytics.\n\nClient/Product: VeeFriends, a prominent web3 NFT project (May 2021); Software Consultant - Assisted in getting the minimum viable product (MVP) across the finish line and successfully launched. Facilitated user experience testing, gathered feedback from Gary Vaynerchuk, and implemented changes based on the feedback. Post-launch, addressed critical bugs, provided user support via email and Discord, and enhanced the application. Technologies utilized: C#, Elasticsearch, and Web3.js."
    },
    {
        "title":"ENGINEERING MANAGER - VIDEO SERVICES PLATFORM TEAM, API TEAM",
        "subtitle":"Alula, St. Paul, Minnesota, October 2021 – February 2022",  
        "body":"Worked with product owner to define and communicate requirements to new camera provider. Designed a secure and scalable solution to integrate new camera provider using AWS. Documented solution into work items and communicated solution with team after soliciting feedback. Provided estimates for completing the integration and highlighted cross team and external dependencies. Worked directly with new camera provider to ensure requirements met the specification and troubleshooted issues. Provided project status updates to project stake holders. Enhanced backend services to support new camera models from existing camera providers. Scaled infrastructure to account for seasonal volume. Maintained and monitored MSK (Kafka) cluster and RDS Postgres cluster for organization. Mentored 3 direct reports and defined a career path to increase employee retention. Transitioned off of the Video Services Platform Team and joined the API Team. Set goals and expectations with new team. Established new processes to increase team sprint velocity, reduce PR dwell time, and decrease time to market. Primary technologies utilized: AWS, Node.js, Terraform."
    },
    {
        "title":"TEAM LEAD - VIDEO SERVICES PLATFORM TEAM",
        "subtitle":"Alula, St. Paul, Minnesota, October 2020 – October 2021",
        "body":"Led mixed team of 5 remote contractors and FTEs consisting of software engineers and quality assurance analysts. Transferred ownership of infrastructure and code for the video services platform from contractors to internal team. Optimized video processing which reduced AWS EC2 compute costs by 80%. Identified and implemented changes to reduce AWS S3 storage costs by 35%. Evaluated multiple incident management software tools. Integrated incident management software into the organizations monitoring and alerting software. Architected, implemented, and load tested new data ingest pipeline for video platform using Kafka to increase scalability, visibility, and ensure system is fault tolerant. Designed and implemented provider agnostic video platform to increase speed to market and decrease integration time. Worked with multiple camera providers to ensure hardware and firmware meet Alula’s specifications. Maintained, monitored, and scaled core infrastructure for organization (MSK Cluster, RDS Postgres instances). Performed database migration in order to consolidate data centers. Implemented HLS (HTTP Live Streaming). Structured the team around scrum/agile fundamentals. Worked with key business stakeholders to build and prioritize backlog. Interviewed, onboarded, and mentored a growing team of software engineers. Primary code utilization included Node.js, Jest, ffmpeg, and Terraform. Amazon Web Services: ECS Fargate, MSK, ECR, EC2 (VPC, ALB, etc), S3, RDS (Postgres), Redis, SQS, and SNS."
    },
    {
        "title":"FULL STACK SOFTWARE ENGINEER - ALULA CONNECT TEAM",
        "subtitle":"Alula, St. Paul, Minnesota, September 2019 – September 2020",
        "body": "Architected and implemented a new time-series data pipeline for organization using Amazon MSK (Kafka), wrote Terraform automation scripts to deploy necessary infrastructure for both the Kafka cluster and consumer ECS cluster. Utilized Terraform to build new monitoring platform for organization, consisting of Prometheus and Grafana, hosted and deployed in AWS. Implemented Prometheus service discoverer for ECS Fargate tasks. Implemented prometheus exporter for Burrow to monitor consumer group metrics. Enhanced and maintained multiple responsive web applications for home automation and smart security platform. Designed, implemented, and tested conditional rendering pattern to facilitate higher application maintainability and scalability (Angular and React compatible). Enhanced and maintained TypeScript library to provide reusable code for multiple applications. Led security initiatives by planning, analyzing, and architecting solutions across web and platform teams. Built out initial patterns and code base for consumer web application using React.js and Redux. Migrated features to new smart security platform to retire old application. Enhanced CI/CD pipeline with automated deployments. Implemented chat bot to facilitate QA processes using the Hubot framework. Primary code utilization included React.js, Redux, TypeScript, Angular, JavaScript, Postgres, Puppeteer, Enzyme, Jest, and Terraform. Amazon Web Services: ECS Fargate, MSK, ECR, EC2 (VPC, ALB, etc), S3, EFS, and CodePipeline."
    },
    {
        "title":"SOFTWARE ENGINEER II - NAVISPHERE VISION TEAM",
        "subtitle":"C.H. Robinson, Eden Prairie, Minnesota, January 2018 - August 2019",
        "body":"Enhanced and maintained eCommerce application that provides customers a view into their global supply chain. Organized and led team of 5 engineers to build custom Alexa Skill and presented it to c-level executives, received budget to expand voice app. Worked closely with data scientists to provide in-app predictive analytics, researched 3rd party APIs, and created proof of concepts. Implemented new customers on a strict deadline. Streamlined customer implementations by designing, implementing, and testing new web application. Reduced customer implementation timelines by leveraging software and driving standardization. Built software to consume multiple sources of data from enterprise service bus (RabbitMQ, Kafka). Worked with infrastructure team to migrate our application to the cloud (Azure). Rewrote application from AngularJS to React.js with Redux. Built npm package to support authentication and authorization that is used across all micro services. As lead engineer on team I mentored a growing team of engineers. Improved teams interview process for multiple roles (SE, BA, QA, PM) and led technical phone screens and on-site interviews. Primary code utilization included React.js, Redux, AngularJS, Node.js (Hapi.js), Docker, SQL, MongoDB, Elasticsearch, Enzyme, Jest, Nightwatch.js, and C# (ServiceStack)."
    },
    {
        "title":"SOFTWARE ENGINEER I - GLOBAL FORWARDING TEAM",
        "subtitle":"C.H. Robinson, Eden Prairie, Minnesota, May 2016 - December 2017",
        "body":"Worked on a team of 5 to design and implement micro-services to send and receive messages from U.S. Customs (ABI CATAIR). Refactored Pre-Arrival Processing System (PAPS) Angular web application with a responsive, mobile first design to enhance UX across wide range of devices used by truck drivers. Contributed to team of ~20 developers by leading Angular training sessions, being DevOps Advocate, and defining code standards for web applications. Built nuget package to support Role Based Access Control (RBAC) using Auth0 and ServiceStack request attributes and plugins. Built shared Angular component library using npm. Leveraged unit tests and automated acceptance(e2e) tests to ensure code quality via CI/CD pipeline. Mentored interns as part of the Intern Program Committee. Primary code utilization included HTML5, Bootstrap, Angular, Protractor.js, Jasmine, C#, ServiceStack, and SQL."
    },
    {
        "title":"PROGRAMMER ANALYST INTERN - GLOBAL FORWARDING TEAM",
        "subtitle":"C.H. Robinson, Eden Prairie, Minnesota, May 2015 - May 2016",
        "body":"Gathered requirements from users, designed, implemented, and tested web application to support team's software deployment process. Used AngularJS, SQL, ServiceStack, C# to develop web application. Built WPF application to reprocess messages, used by our support team. Worked remotely for half of the internship where I contributed to sprint work along side scrum team. Sprint work included enhancing and maintaining large VB .NET application and building out new web applications to support the needs of the growing Global Forwarding Division. Presented products/work to executives, managers, and various teams."
    },
    {
        "title":"SOFTWARE ENGINEER",
        "subtitle":"TenEx, LLC, Platteville, Wisconsin , February 2015 - August 2015",
        "body":"Designed and implemented analytics solution to help understand user behavior and rate of adoption. Created daily and weekly reports using Java and MySql with Slack integrations."
    },
    {
        "title":"SOFTWARE ENGINEER INTERN",
        "subtitle":"Danfoss, Loves Park, Illinois, May 2014 - August 2014",
        "body":"Designed and implemented embedded Wi-Fi communication system with mobile interface. Prototyped using ST Discovery Kit microcontroller and Wi-Fi module. Primary code utilization included HTML5, CSS3, JavaScript, and C."
    }
];
export default content;